# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4iOYsZqRVDvgI8CK1xmKJqy16zWf6M4
"""

# First, install the forex-python library if not already installed:
# pip install forex-python

from forex_python.converter import CurrencyRates

# Create an instance of the CurrencyRates class
c = CurrencyRates()

print("🌍 Welcome to the Real-Time Currency Converter!")

while True:
    # Step 1: Get user input
    from_currency = input("Enter the currency you want to convert from (e.g., USD): ").upper()
    to_currency = input("Enter the currency you want to convert to (e.g., INR): ").upper()

    # Step 2: Get the amount to convert
    amount_str = input(f"Enter the amount in {from_currency}: ")

    # Validate amount input
    try:
        amount = float(amount_str)
    except ValueError:
        print("❌ Please enter a valid number.")
        continue

    # Step 3: Perform conversion using live rates
    try:
        converted_amount = c.convert(from_currency, to_currency, amount)
        print(f"💱 {amount} {from_currency} = {converted_amount:.2f} {to_currency}")
    except Exception as e:
        print(f"⚠️ Error: {e}")
        continue

    # Step 4: Ask if the user wants to do a reverse conversion
    reverse = input(f"Do you want to convert {to_currency} back to {from_currency}? (yes/no): ").lower()
    if reverse == "yes":
        reverse_amount = c.convert(to_currency, from_currency, converted_amount)
        print(f"💱 {converted_amount:.2f} {to_currency} = {reverse_amount:.2f} {from_currency}")

    # Step 5: Ask if the user wants to continue
    again = input("Do you want to convert another amount? (yes/no): ").lower()
    if again != "yes":
        print("✈️ Safe travels! Goodbye!")
        break